### ISSUE TITLE
crashing after new uodate on 8/7/2021

### ISSUE THREAD

**Issue by ankit131199** [doonayy/fortheboys#10]
pls update .

**Comment by Wristing** [comment]
> pls update .

its not his fault. the official dll hasnt even beed updated how do u want him to fix his fork?

**Comment by cooldog14** [comment]
should be good, dont use glow tho. Thank you @Wristing for keeping people updated

**Comment by vector199** [comment]
it crashes even with glow lol

**Comment by Wristing** [comment]
> 
> 
> it crashes even with glow lol

you mean without?

**Comment by Wristing** [comment]
edit: its not crashing anymore, 1st inject usually crashes and 2nd works without any crashes

~~its crashing for me as well, the one button works because it restarts steam, vac bypass gets initiated but when the game opens it crashes after a few~~
