### ISSUE TITLE
.dll not injecting

### ISSUE THREAD

**Issue by jakbes** [doonayy/fortheboys#11]
VAC bypa$$ runs fine, dll link and the dll itself is fine

**Comment by cooldog14** [comment]
if everything is fine, what's wrong ?

**Comment by jakbes** [comment]
> if everything is fine, what's wrong ?

the loader itself doesnt inject the dll, tried with several dlls

**Comment by cooldog14** [comment]
Fair, add me on dc, I’ll check that this evening

**Comment by cooldog14** [comment]
did you tried to mess with the wait before injecting ? iirc it wait a bunch after waiting for the csgo process
