### ISSUE TITLE
crashing on inject

### ISSUE THREAD

**Issue by AkkayaKaan** [doonayy/fortheboys#12]
the game crashes

**Comment by cooldog14** [comment]
prolly the .dll

**Comment by AkkayaKaan** [comment]
no its not dll. Are you sure injector is still working ?

**Comment by cezacs1** [comment]
can u fix injector?

**Comment by AkkayaKaan** [comment]
yea @doonayy can you fix it ?

**Comment by cooldog14** [comment]
I'm not working on this injector until I find a new free cheat to use. You could revert to an older version if you want. C# is really easy to understand.
