### ISSUE TITLE
Detected?

### ISSUE THREAD

**Issue by SatanicScripter** [doonayy/fortheboys#13]
Is it detected? And also where i can find the cheats?
Thanks

**Comment by SatanicScripter** [comment]
bro you dont have comment my issue

**Comment by Wristing** [comment]
> bro you dont have comment my issue

here comes the two month late comment:
i dont mean to insult you by any means but you are the one wrong here, u arent giving an  issue but asking a retarded question.
stay safe.

**Comment by cooldog14** [comment]
Thank you @Wristing
