### ISSUE TITLE
Injection method incompatible with the legit bot fix

### ISSUE THREAD

**Issue by cooldog14** [doonayy/fortheboys#2]
I need to update the injection method to make it work, no clue how tho

**Comment by Wristing** [comment]
> I need to update the injection method to make it work, no clue how tho

it's the dll so u probably only need to update it? i can also try to check that later today

edit: spelling

**Comment by cooldog14** [comment]
yea, i know it's the dll who mess up the old injection method. That's why i reverted to an older version of otc

**Comment by cooldog14** [comment]
alright the latest .dll fixed everything 😎

**Comment by zxnnas** [comment]
It continues to crash, im using the simpleloader, do i need to switch over to the injector and download the dll?

**Comment by Wristing** [comment]
> It continues to crash, im using the simpleloader, do i need to switch over to the injector and download the dll?

new update fucked up the stuff because just yesterday it was working

unless im doing something wrong

**Comment by cooldog14** [comment]
it does indeed crash at launch, i tested it yesterday and it was working fine

**Comment by cooldog14** [comment]
new dll fixed the crashing issue 😎

**Comment by zxnnas** [comment]
what should i do to fix this? redownload the simple loader? or download the dll and get a injector?

**Comment by cooldog14** [comment]
I have no clue, try using different injector, different csgo settings, it works on my end. Also it should always use the latest .dll unless I upload the .dll with a wrong name.

**Comment by cooldog14** [comment]
Here are my cs settings : https://cdn.discordapp.com/attachments/740625592013029497/839229626857553960/unknown.png

**Comment by zxnnas** [comment]
ty goodsir

**Comment by cooldog14** [comment]
it works ?

**Comment by zxnnas** [comment]
yessirr

**Comment by zxnnas** [comment]
redownloaded the simple loader and changed my settings, ty for the helppp

**Comment by cooldog14** [comment]
Niceee, happy to help :)
