### ISSUE TITLE
"Inject" button does not work.

### ISSUE THREAD

**Issue by KorblesD** [doonayy/fortheboys#3]
Clicking "inject" doesn't do anything. I'm assuming this has to do with the new CS:GO update?

**Comment by cooldog14** [comment]
https://cdn.discordapp.com/attachments/740625592013029497/841443115558633542/unknown.png

no clue still inject on my end

**Comment by cooldog14** [comment]
is it working ?

**Comment by cooldog14** [comment]
cool

**Comment by Wristing** [comment]
> cool

ive never had an issue, besides that one update recently, but since then all good for me

**Comment by cooldog14** [comment]
good to know thank you for the feedback, i'd like to make the whole process in one button, i have a lot of exams rn, i ll see that later

**Comment by Wristing** [comment]
> good to know thank you for the feedback, i'd like to make the whole process in one button, i have a lot of exams rn, i ll see that later

yeah imo you dont need really to worry about it
