### ISSUE TITLE
Pressing thirdperson crashes my game

### ISSUE THREAD

**Issue by Zxnna** [doonayy/fortheboys#4]
it may just be on my end but when i press the thirdperson button it completely crashes, ive reset everything ive deleted all scripts and cfgs, ive deleted csgo ive verified files but it continues to crash, anyway to fix it?

**Comment by Zxnna** [comment]
nvm everytime i toggle something the game crashes so its not just third person

**Comment by cooldog14** [comment]
yup there is a new version of otc3, i'll update it asap

**Comment by Zxnna** [comment]
ty good sir
