### ISSUE TITLE
still crashing 

### ISSUE THREAD

**Issue by Zxnna** [doonayy/fortheboys#5]
loading a cfg which only has two js's that are small, and when i shoot someone it crashes is it on my end? sorry for bother

**Comment by Wristing** [comment]
i heard some features even with updated dll werent working, not sure tho, sorry i cant test it today neither

**Comment by Zxnna** [comment]
arl np ty

**Comment by cooldog14** [comment]
Apparently JavaScript makes otc3 crash, try to keep them at a minimum
